# This is a basic workflow to help you get started with Actions

name: HyperShift CI Trigger

# Controls when the workflow will run
on:
  schedule:
    # Runs "8:30AM each day" (see https://crontab.guru)
    - cron: '30 12 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  query:
    runs-on: ubuntu-latest
    steps:
    - name: Run a one-line script
      uses: actions/checkout@v3
    - name: Query Quay.io
      id: quay
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://quay.io/api/v1/repository/stolostron/acm-custom-registry/tag/?limit=2'
        method: 'GET'
        customHeaders: '{"Content-Type": "application/json"}'
    - name: Show Response
      run: |
        echo snapshot=$(echo ${{ toJson(steps.quay.outputs.response) }} | jq '[ .tags[].name] | map(select(. | startswith("2.6.0-SNAPSHOT")))' | jq .[0])
        echo ${{ env.snapshot }} > snapshot.txt
        git add snapshot.txt
        git commit -s -m ${{ env.snapshot }}

        
