# This is a basic workflow to help you get started with Actions

name: HyperShift CI Trigger

# Controls when the workflow will run
on:
  schedule:
    # Runs "8:30AM each day" (see https://crontab.guru)
    - cron: '30 12 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  query:
    runs-on: ubuntu-latest
    steps:
    - name: Query Quay.io
      id: quay
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://quay.io/api/v1/repository/stolostron/acm-custom-registry/tag/?limit=10'
        method: 'GET'
        customHeaders: '{"Content-Type": "application/json"}'
    - name: Show Response
      run: |
        echo ${{ steps.quay.outputs.response }}
        echo ${{ fromJson(steps.quay.outputs.response).field_you_want_to_access }}
  commit:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Update build

        
